/**
 * Machine-readable error codes (docs/04-api-design.md §7).
 *
 * Clients branch on `code`, never on `message`. Messages are human-readable and
 * localisable; codes are a stable contract.
 */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_VALUE: 'DUPLICATE_VALUE',
  ASSET_ALREADY_ASSIGNED: 'ASSET_ALREADY_ASSIGNED',
  STALE_WRITE: 'STALE_WRITE',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  ENTITLEMENT_EXCEEDED: 'ENTITLEMENT_EXCEEDED',
  SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_INACTIVE',
  RESOURCE_IN_USE: 'RESOURCE_IN_USE',
  LAST_OWNER: 'LAST_OWNER',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
